version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage:z

  document-registry-service:
    build:
      context: ./vector
      dockerfile: Dockerfile
    container_name: vector_service
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./models_cache:/app/models_cache  # Shared model cache
    depends_on:
      qdrant:
        condition: service_started
    restart: unless-stopped

  agent-service:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent_service
    env_file: .env
    ports:
      - "8501:8501"
    volumes:
      - ./models_cache:/app/models_cache  # Shared model cache
    depends_on:
      qdrant:
        condition: service_started
      document-registry-service:
        condition: service_started
    restart: unless-stopped

volumes:
  qdrant_data: {}