# docker-compose.yml

version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage:z

  document-registry-service:
    build:
      context: ./vector
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
     - qdrant


volumes:
  qdrant_data: {}
